vich_uploader:
    db_driver: orm

    mappings:
        picture_project:
                    uri_prefix: /images/pictures
                    upload_destination: '%upload_directory%'
                    namer: Vich\UploaderBundle\Naming\UniqidNamer
        cover_file:
                    uri_prefix: /images/cover
                    upload_destination: '%upload_directory%'
                    namer: Vich\UploaderBundle\Naming\UniqidNamer
