vich_uploader:
    db_driver: orm

    mappings:
       picture_project:
                    # alias qui nous permet d'accéder à nos images depuis le navigateur
                    uri_prefix: /images/posters
                    # Chemin vers le dossier de stockage
                    upload_destination: '%upload_directory%'
                    namer: Vich\UploaderBundle\Naming\UniqidNamer
